### ISSUE TITLE
Face texture issue with whole body fitting

### ISSUE THREAD

**Issue by ujjawalcse** [YadiraF/PIXIE#26]
Hey,
Congrats for this great work.
I tested this repository and glad to see the results.

I'm experimenting with different options given as arguments, so i executed the below command,
 `python demos/demo_fit_body.py -i test_samples1/ -s test_samples1_result/ --deca_path DECA/ --extractTex True --saveObj True`

But the resultant texture is not mapping correctly to the given template and hence getting very poor facial texture.
Below are some references -
input 1

![bill-gates-7](https://user-images.githubusercontent.com/32773256/163134143-5a73bbf6-c9ee-4cf8-849e-1cc2ecbac01a.jpg)

output 1

![bill-gates-7](https://user-images.githubusercontent.com/32773256/163134244-c4d16f59-3dbb-41c4-9927-c03947c98520.png)

input 2
![elon_musk](https://user-images.githubusercontent.com/32773256/163134345-ad37c56f-8a63-40be-8b35-25ee77892c43.jpeg)

output 2
![elon_musk](https://user-images.githubusercontent.com/32773256/163134473-6f347d0b-1d85-49d5-822f-0fe764d2ac84.png)

input 3
 
![thumb_bezos](https://user-images.githubusercontent.com/32773256/163134555-4b77b5b8-7792-4fe5-92d7-0f0a01773bad.png)

output 3
![thumb_bezos](https://user-images.githubusercontent.com/32773256/163134618-e1e32041-c23e-4639-ad36-240813f2f1cd.png)

Can you please suggest some ways to enhance the results?

Thanks.

**Comment by amramer** [comment]
Hi @ujjawalcse when I use the argument --deca_path  DECA/ I got the following error: (please do you have any suggested solutions?)

Traceback (most recent call last):
  File "demos/demo_fit_body.py", line 173, in <module>
    main(parser.parse_args())
  File "demos/demo_fit_body.py", line 76, in main
    _, deca_opdict, _ = deca.run(cropped_face_savepath)
  File "DECA/decalib/deca.py", line 318, in run
    opdict, visdict = self.decode(codedict)
  File "DECA/decalib/deca.py", line 241, in decode
    if self.cfg.model.extract_tex:
  File "/home/amr/anaconda3/envs/pixie-env/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: extract_tex

**Comment by RayShing** [comment]
> Hi @ujjawalcse when I use the argument --deca_path DECA/ I got the following error: (please do you have any suggested solutions?)
> 
> Traceback (most recent call last): File "demos/demo_fit_body.py", line 173, in main(parser.parse_args()) File "demos/demo_fit_body.py", line 76, in main _, deca_opdict, _ = deca.run(cropped_face_savepath) File "DECA/decalib/deca.py", line 318, in run opdict, visdict = self.decode(codedict) File "DECA/decalib/deca.py", line 241, in decode if self.cfg.model.extract_tex: File "/home/amr/anaconda3/envs/pixie-env/lib/python3.7/site-packages/yacs/config.py", line 141, in **getattr** raise AttributeError(name) AttributeError: extract_tex

Same issue. Have you found any solutions? Thanks!
