### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by Mihailllll** [YadiraF/PIXIE#27]
Hi! 
I have configured cuda and torch of other versions, because my system requires it.
I wont start body example, but get this error:

total 12 images
creating the SMPLX Decoder
Traceback (most recent call last):
  File "demos/demo_fit_body.py", line 165, in <module>
    main(parser.parse_args())
  File "demos/demo_fit_body.py", line 35, in main
    pixie = PIXIE(config = pixie_cfg, device=device)
  File "/home/owner/PythonProjects/3dBodyFromImage/4/PIXIE/pixielib/pixie.py", line 50, in __init__
    self._create_model()
  File "/home/owner/PythonProjects/3dBodyFromImage/4/PIXIE/pixielib/pixie.py", line 108, in _create_model
    self.smplx = SMPLX(self.cfg.model).to(self.device)
  File "/home/owner/PythonProjects/3dBodyFromImage/4/PIXIE/pixielib/models/SMPLX.py", line 156, in __init__
    self.extra_joint_selector = JointsFromVerticesSelector(
  File "/home/owner/PythonProjects/3dBodyFromImage/4/PIXIE/pixielib/models/lbs.py", line 399, in __init__
    data = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'

Please, help fix this.

**Comment by Mihailllll** [comment]
It's fix this error
from yaml import Loader
            with open(fname, 'r') as f:
                data = yaml.load(f,  Loader=Loader)

**Comment by ZihanGao777** [comment]
I have the same question.
