### ISSUE TITLE
FLAME texture array reshape error 

### ISSUE THREAD

**Issue by nitish11** [YadiraF/PIXIE#51]
I am getting following error in all the demo codes. 
`

> PIXIE> python demos/demo_animate_body.py
> total 1 images
> total 6 images
> creating the SMPLX Decoder
> Traceback (most recent call last):
>   File "demos/demo_animate_body.py", line 150, in <module>
>     main(parser.parse_args())
>   File "demos/demo_animate_body.py", line 37, in main
>     pixie = PIXIE(config = pixie_cfg, device=device)
>   File "~\PIXIE\pixielib\pixie.py", line 50, in __init__
>     self._create_model()
>   File "~\PIXIE\pixielib\pixie.py", line 112, in _create_model
>     self.flametex = FLAMETex(self.cfg.model).to(self.device)
>   File "~\PIXIE\pixielib\models\FLAME.py", line 38, in __init__
>     texture_basis = tex_space[pc_key].reshape(-1, n_pc)
> ValueError: cannot reshape array of size 114032640 into shape (199)

`

**Comment by nitish11** [comment]
This error was coming the model file was corrupt. Please check the model file.
